### ISSUE TITLE
Using ECAL Shared Memory between Multiple Docker Containers

### ISSUE THREAD

**Issue by JeremyBYU** [continental/ecal#238]
**Describe the bug**

This most likely is not  a bug with ECAL but thought I would share and get some ideas. I am building a "publisher" and "subscriber" application, called 'rs-pub' and 'rs-integrate' respectively (same topic). These are already tested and working locally on a computer  and communicate via shared memory. I can also build and launch ONE docker container that will run the publisher with [shared memory access to the host](https://stackoverflow.com/questions/23889187/is-it-possible-to-share-memory-between-docker-containers).  I can run `ecal-mon-gui` on the local desktop and it will subscribe (with shared memory!) to the producing topic on the docker container. 

Now things get interesting. I can now [attach](https://stackoverflow.com/a/27708039) to the existing docker container (the publisher) and then launch a new "subscriber" process (rs-integrate). Since they are in the same container everything works as expected and `rs-integrate` gets the topic through shared memory. The local desktop through `ecal-mon-gui` can still subscribe through shared memory (yay!).

Now the question becomes: can I launch two separate docker containers, both connected to the host shared memory, and still have everything work? No, for some reason it doesn't seem to work. Here is the docker compose file that performs this function (it will just launch two containers and run the pub and subscribe applications).

```yaml
version: "3.3"  # optional since v1.27.0
services:
  # This will connect to realsense devices and publish. Configured with config/l515/rspub_default.toml
  rs-pub:
    container_name: rs-pub
    image: "jeremybyu/realsense:latest"
    privileged: true
    network_mode: "host"
    ipc: "host"
    # ipc: shareable
    volumes:
      - $PWD:/opt/workspace
    command: ./bin/x86_64/rs-pub --log_dir=./logs --v=2 --config=config/l515/rspub_default.toml
  # This is an RPC Server that is also subscribing to any RGBD Images that are published. Configured with config/l515/rsintegrate_default.toml
  rs-integrate:
    container_name: rs-integrate
    image: "jeremybyu/realsense:latest"
    privileged: true
    network_mode: "host"
    ipc: "host"
    # ipc: "container:rs-pub"
    volumes:
      - $PWD:/opt/workspace
    depends_on:
        - rs-pub
    entrypoint: []
    command: bash -c "export OMP_NUM_THREADS=1 && sleep 5 && ./bin/x86_64/rs-integrate-server --log_dir=./logs --v=2 --config=config/l515/rsintegrate_default.toml"
```

Using `ecal_mon_gui` (on the local desktop) I can see that they "maybe" see each other. But the subscriber is just not seeing the messages.  I know this not just from ecal-mon but the subscriber application is not printing to stdout any received messages. Do note that the local desktop is still able to see the messages through shared memory. Just not the subscribing docker container.

![image](https://user-images.githubusercontent.com/6628085/112557648-53cc0f80-8da3-11eb-89dd-a58cfde96a3b.png)

So I'm kind of bummed because I thought that this would work if all the containers shared the hosts shared memory name space.Also note that I tried different "ipc" modes such as "shareable" and it still didn't work. 

I'm just wondering if I am missing something obvious to make shared memory work across docker containers. Have you ever tried anything like this before? Also [here is a drop dead simple example](https://github.com/JeremyBYU/docker_shm_test) of using shared memory between two docker containers (it works). This may help to compare and contrast what ECAL is doing. 

EDIT: 
Couple other thoughts: What else besides shared memory does ECAL need access to succesfully share messages. TCP? UDP? DNS resolution? I guess I need to think about all those other pieces. I did already state that they containers should be using the same host network.

EDIT 2:
HA! Did some more digging and I believe the issue is with `docker-compose`. When I manually launch to seperate containers then everything works. For example like this:
1. `docker run  --rm --privileged -it --env="DISPLAY" --net=host --volume="/tmp/.X11-unix:/tmp/.X11-unix:rw" --mount type=bind,source="$(pwd)",target=/opt/workspace --name realsense1 --user $(id -u):$(id -g) --ipc=host jeremybyu/realsense:latest` . Then launch publisher
2. `docker run  --rm --privileged -it --env="DISPLAY" --net=host --volume="/tmp/.X11-unix:/tmp/.X11-unix:rw" --mount type=bind,source="$(pwd)",target=/opt/workspace --name realsense2 --user $(id -u):$(id -g) --ipc=host jeremybyu/realsense:latest` . Then launch subscriber

So must be something with docker-compose. Ignore this issue for now. I will ping if I get something later and probably close.

**Desktop:**
 - OS: Ubuntu 18.04
 - ECAL 5.8.5

ecal ini file just in case:

```ini
; ---------------------------------------------
; NETWORK SETTINGS
; ---------------------------------------------
;
; network_enabled      = true / false         true  = all eCAL components communicate over network boundaries
;                                             false = local host only communication
;
; multicast_group      = 239.0.0.1            UDP multicast group base
;
; multicast_mask       = 0.0.0.1-0.0.0.255    Mask maximum number of dynamic multicast group
;
; multicast_port       = 14000 + x            UDP multicast port number (eCAL will use at least the 2 following port
;                                             numbers too, so please modify in steps of 10 (e.g. 1010, 1020 ...)
;
; multicast_ttl        = 0 + x                UDP ttl value, also known as hop limit, is used in determining 
;                                             the intermediate routers being traversed towards the destination
;
; multicast_sndbuf    = 1024 * x              UDP send buffer in bytes
;  
; multicast_rcvbuf    = 1024 * x              UDP receive buffer in bytes
;  
; unicast_ipaddr      = 127.0.0.1             UDP unicast group for eCAL unicast
; unicast_port        = 15000                 UDP unicast port number for eCAL unicast
; 
; bandwidth_max_udp   = 1048576               UDP bandwidth limit for eCAL udp layer (-1 == unlimited)
;  
; inproc_rec_enabled  = true                  Enable to receive on eCAL inner process layer
; shm_rec_enabled     = true                  Enable to receive on eCAL shared memory layer
; udp_mc_rec_enabled  = true                  Enable to receive on eCAL udp multicast layer
; udp_uc_rec_enabled  = false                 Enable to receive on eCAL udp unicast layer
; lcm_rec_enabled     = false                 Enable to receive on Google lcm layer
; rtps_rec_enabled    = false                 Enable to receive on FastRtps layer (ROS2)
; iceoryx_rec_enabled = false                 Enable to receive on Iceoryx layer
;
; npcap_enabled       = false                 Enable to receive UDP traffic with the Npcap based receiver
; ---------------------------------------------

[network]
network_enabled     = true
multicast_group     = 224.0.0.1
multicast_mask      = 0.0.0.15
multicast_port      = 14000
multicast_ttl       = 3
multicast_sndbuf    = 5242880
multicast_rcvbuf    = 5242880

multicast_group_mtl = 224.0.0.1
multicast_port_mtl  = 14100

unicast_ipaddr      = 127.0.0.1
unicast_port        = 15000

bandwidth_max_udp   = -1

inproc_rec_enabled  = true
shm_rec_enabled     = true
udp_mc_rec_enabled  = true
udp_uc_rec_enabled  = false
lcm_rec_enabled     = false
rtps_rec_enabled    = false
iceoryx_rec_enabled = false

npcap_enabled       = false

; ---------------------------------------------
; COMMON SETTINGS
; ---------------------------------------------
;
; registration_timeout = 1000 + (x * 1000)           timeout for topic registration in ms
;
; registration_refresh < registration_timeout/2      topic registration refresh cylce (has to be smaller then registration timeout !)
;
; ---------------------------------------------
[common]
registration_timeout  = 60000
registration_refresh  = 1000

; ---------------------------------------------
; TIME SETTINGS
; ---------------------------------------------
;
; timesync_module_rt        = "ecaltime-localtime"   module (dll|so) name time sync interface.
;                                                    The name will be extended with platform suffix (32|64),
;                                                    debug suffix (d) and platform extension (.dll|.so)
;                                                    
;                                                    Available modules are:
;                                                      - ecaltime-localtime    local system time without synchronization        
; ---------------------------------------------
[time]
timesync_module_rt        = "ecaltime-localtime"

; ---------------------------------------------
; RTPS SETTINGS
; ---------------------------------------------
;
; domain                    = "eCAL"                 default fastRTPS domain name
;
; ---------------------------------------------
[rtps]
domain                    = "eCAL"

; ---------------------------------------------
; ICEORYX SETTINGS
; ---------------------------------------------
;
; service                   = "eCAL"                 default Iceoryx service name
; instance                  = ""                     default Iceoryx service instance name
;
; ---------------------------------------------
[iceoryx]
service                   = "eCAL"
instance                  = ""

; ---------------------------------------------
; PUBLISHER SETTINGS
; ---------------------------------------------
;
; use_inproc                = 0, 1, 2                use inner process transport layer (0 = off, 1 = on, 2 = auto, default = 0)
; use_shm                   = 0, 1, 2                use shared memory transport layer (0 = off, 1 = on, 2 = auto, default = 2)
; use_udp_mc                = 0, 1, 2                use udp multicast transport layer (0 = off, 1 = on, 2 = auto, default = 2)
; use_udp_uc                = 0, 1                   use udp unicast transport layer   (0 = off, 1 = on,           default = 0)
; use_lcm                   = 0, 1                   use lcm transport layer           (0 = off, 1 = on,           default = 0)
; use_rtps                  = 0, 1                   use rtps transport layer          (0 = off, 1 = on            default = 0)
; use_iceoryx               = 0, 1                   use iceoryx transport layer       (0 = off, 1 = on            default = 0)
;
; memfile_minsize           = x * 4096 kB            default memory file size for new publisher
;
; memfile_reserve           = 20 .. x %              dynamic file size reserve before recreating memory file if topic size changes
;
; memfile_ack_timeout       = 0 .. x ms              publisher timeout for ack event from subscriber that memory file content is processed
;
; share_ttype               = 0, 1                   share topic type via registration layer
; share_tdesc               = 0, 1                   share topic description via registration layer
;                                                    switch off to disable reflection
; ---------------------------------------------
[publisher]
use_inproc                = 0
use_shm                   = 2
use_udp_mc                = 2
use_udp_uc                = 0
use_lcm                   = 0
use_rtps                  = 0
use_iceoryx               = 0

memfile_minsize           = 4096
memfile_reserve           = 50
memfile_ack_timeout       = 0

share_ttype               = 1
share_tdesc               = 1

; ---------------------------------------------
; MONITORING SETTINGS
; ---------------------------------------------
;
; timeout          = 1000 + (x * 1000)               timeout for topic monitoring in ms
; filter_excl      = Message1, Message2              topics blacklist as regular expression (will not be monitored)
; filter_incl      = Message1, Message2              topics whitelist as regular expression (will be monitored only)
; filter_log_con   = info, warning, error            log messages to console (all, info, warning, error, fatal, debug1, debug2, debug3, debug4)
; filter_log_file  = debug1, debug2                  log messages to log file
; filter_log_udp   = all                             log messages to udp bus
;
; ---------------------------------------------
[monitoring]
timeout            = 5000
filter_excl        = __.*
filter_incl        =
filter_log_con     = error, fatal
filter_log_file    =
filter_log_udp     = info, warning, error, fatal

; ---------------------------------------------
; SYS SETTINGS
; ---------------------------------------------
;
; filter_excl      = App1,App2                       apps blacklist to be excluded when importing tasks from cloud
;
; ---------------------------------------------
[sys]
filter_excl        = ^eCALRPCService$|^eCALMon$|^eCALPlay$|^eCALPlayGUI$|^eCALRec$|^eCALRecGUI$|^eCALSys$|^eCALSysGUI$|^Machine Monitoring Agent|^Any \(LCM\)$

```

**Comment by FlorianReimold** [comment]
Hi Jeremy,

Great, that you already have been able to solve the issue yourself! I don't have much knowledge about docker, but I wanted to answer your question regarding what is behind eCAL to make a working message transfer:

UDP Multicast is used to tell about the presence of a topic.
UDP Multicast is also used to request the subscription of a topic.
Shared Memory is then used for transmitting the raw data only.

So in your docker setup, you still need to have bi-directional UDP multicast working. In a "normal" local setup, you would have to set the multicast routes to an existing network interfaces or the the loopback interface (as described [here](https://continental.github.io/ecal/getting_started/cloud.html#fa-ubuntu-multicast-configuration-on-ubuntu)).

**Comment by rex-schilasky** [comment]
@JeremyBYU Your ecal ini file is really outdated. Please check on all your host that eCAL is not using a mix of older and newer eCAL configuration files. You can check in the monitor which one is used and where it is located.

![image](https://user-images.githubusercontent.com/49162693/112619682-e4e4ca00-8e27-11eb-804e-3794877447a2.png)

In the eCAL 5.8 series the configuration is reduced to that [one](https://github.com/continental/ecal/blob/master/ecal/core/cfg/ecal.ini).

**Comment by JeremyBYU** [comment]
Thank you both for your help. I will go ahead and update the ECAL.ini file and see if that helps.

I still can't get it to exactly work with docker-compose. However the containers launched by docker-compose themselves seem to be set up appropriately. If docker-compose only "launches" the containers and then I manually "terminal into" them and start the programs manually everything is working. So maybe something to do with launching the processes? I have already added timer delays for the subscriber process not sure what it is. Very peculiar!

I'll update if I figure it out.

**Comment by JeremyBYU** [comment]
Okay I have a "fix" for it now. It looks like I have to launch the program as a bash script in the immediate entry point. There is something about ECAL wanting to be launched inside a terminal. Here is the final config and launch file:

```yml
version: "3.3"  # optional since v1.27.0
services:
  # This will connect to realsense devices and publish. Configured with config/l515/rspub_default.toml
  rs-pub:
    container_name: rs-pub
    image: "jeremybyu/realsense:latest"
    privileged: true
    network_mode: "host"
    ipc: "host"
    user: "1000:1000"
    volumes:
      - $PWD:/opt/workspace
    command: ./bin/x86_64/rs-pub --log_dir=./logs --v=2 --config=config/l515/rspub_default.toml
  # This is an RPC Server that is also subscribing to any RGBD Images that are published. Configured with config/l515/rsintegrate_default.toml
  rs-integrate:
    container_name: rs-integrate
    image: "jeremybyu/realsense:latest"
    privileged: true
    network_mode: "host"
    ipc: "host"
    user: "1000:1000"
    volumes:
      - $PWD:/opt/workspace
    depends_on:
        - rs-pub
    entrypoint: [./scripts/launch/launch_integrate.sh]
```

```bash
#!/bin/bash
# For some reason the rs-integrate service will ONLY work if launched as an entry point!
# https://github.com/continental/ecal/issues/238
cd /opt/workspace
export OMP_NUM_THREADS=1
echo "Delaying startup for 5 seconds"
sleep 5
./bin/x86_64/rs-integrate-server --log_dir=./logs --v=2 --config=config/l515/rsintegrate_default.toml
```
