### ISSUE TITLE
eCAL Cloud Configuration Not Sending/Receiving Data Correctly

### ISSUE THREAD

**Issue by JeffreyZh4ng** [continental/ecal#650]
Currently I have two machines on the same LAN that both send out multicasts to one another via two different streams using eCAL in Cloud Mode. After configuring the network shown in the documentation ([here](https://continental.github.io/ecal/getting_started/cloud.html#fa-ubuntu-multicast-configuration-on-ubuntu)), neither the server or device is able to receive multicast messages from one another. 

- The programs running on the server and device work when eCAL is in Local Mode and both the server and device are on the same machine which suggests the issue is with the network configuration.  
- I tried setting up the network configuration using both netplan and the GUI method shown in the documentation; neither method worked. 
- Using the eCAL monitor GUI, I saw that messages were being written to the topic on the device, but none of those messages were being received on the server which was subscribed to that topic.
- ecal_sample_person_snd and ecal_sample_person_rec were each tested on each machine and there were no issues there.

Other details:
- Both machines are connected to the network using a WiFi dongle
- Using Google Protobuf
- Code (I'm not doing anything complicated at all): [device tx](https://github.com/ILLIXR/ILLIXR/blob/feat-offloading-release/offload_vio/device_tx/plugin.cpp#L20-L21), [server rx](https://github.com/ILLIXR/ILLIXR/blob/feat-offloading-release/offload_vio/server_rx/plugin.cpp#L20-L22)

/etc/netplan/50-ecal-multicast.yaml on the device (server is the same just with a different static IP)
```
# Replace eth0 with your network adapter!
network:
  version: 2
  renderer: NetworkManager # GUI integration for desktop Ubuntu
  ethernets:

    # Replace eth0 with your interface!
    wlan0:

      # Either use DHCP...
      dhcp4: no
      dhcp6: no

      # ... or configure a static address!
      addresses:
        - 10.6.3.148/24

      routes:
        - to: 239.0.0.0/24
          via: 0.0.0.0
          metric: 1
```
          

ecal.ini (Same on both machines. Cloud mode on, hops to 10, only cloud mode enabled)
```
[network]
network_enabled           = true
multicast_group           = 239.0.0.1
multicast_mask            = 0.0.0.15
multicast_port            = 14000
multicast_ttl             = 10
multicast_sndbuf          = 5242880
multicast_rcvbuf          = 5242880

bandwidth_max_udp         = -1

inproc_rec_enabled        = false
shm_rec_enabled           = false
udp_mc_rec_enabled        = true

npcap_enabled             = false

[publisher]
use_inproc                = 0
use_shm                   = 0
use_udp_mc                = 1
```

Loopback file is the same as whats shown in the documentation.

If anyone has insight into how to get this working it would be greatly appreciated as I've been stuck on this issue for quite some time.
